# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:title/

# Setup
title:            The DevOps Ninja
tagline:          'Think DevOps'
description:      ''
url:              https://thedevops.ninja
baseurl:          /

author:
  name:           'Pragith Prakash'
  url:            https://thedevops.ninja

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pragith

plugins:
  - jekyll-paginate